- name: Install python-virtualenv
  apt: name={{ item }}
  with_items:
    - python-virtualenv
  ignore_errors: yes

- name: Install virtualenv
  apt: name={{ item }}
  with_items:
    - virtualenv
  ignore_errors: yes

- name: Install Docker Compose 1.7.x
  pip:
    name: docker-compose>=1.7,<1.8
    virtualenv: /opt/compose-1.7
  when: compose_version == '1.7'

- name: Install Docker Compose 1.8.x
  pip:
    name: docker-compose>=1.8,<1.9
    virtualenv: /opt/compose-1.8
  when: compose_version == '1.8'

- file: src="/opt/compose-{{ compose_version }}/bin/docker-compose" dest=/usr/local/bin/docker-compose state=link force=yes
