- name: Install python-virtualenv
  apt: name={{ item }}
  with_items:
    - python-virtualenv
  ignore_errors: yes

- name: Install virtualenv
  apt: name={{ item }}
  with_items:
    - virtualenv
  ignore_errors: yes

- name: Install Docker Compose
  pip:
    name: docker-compose
    version: 1.8.1
    virtualenv: /opt/compose-1.8
  when: compose_version == '1.8'

- file: src="/opt/compose-{{ compose_version }}/bin/docker-compose" dest=/usr/local/bin/docker-compose state=link force=yes
